name: PHP Test CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        php-versions:
          - { version: '5.6', require: 'shivammathur/setup-php@v2' }
          - { version: '7.0', require: 'shivammathur/setup-php@v2' }
          - { version: '7.1', require: 'shivammathur/setup-php@v2' }
          - { version: '7.2', require: 'shivammathur/setup-php@v2' }
          - { version: '7.3', require: 'shivammathur/setup-php@v2' }
          - { version: '7.4', require: 'shivammathur/setup-php@v2' }
          - { version: '8.0', require: 'shivammathur/setup-php@v2' }
        phpunit-versions: ['latest']
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: ${{ matrix.php-versions.require }}
        with:
          php-versions: ${{ matrix.php-versions.version }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: ./vendor/bin/phpunit
